Fix clang format
Signed-off-by: Ping Xie <pingxie@google.com>

diff --git a/.github/workflows/clang-format.yml b/.github/workflows/clang-format.yml
--- a/.github/workflows/clang-format.yml
+++ b/.github/workflows/clang-format.yml
@@ -41,8 +41,19 @@ jobs:
     - name: Check for formatting changes
       if: ${{ steps.clang-format.outputs.diff }}
       run: |
-        echo "Code is not formatted correctly. Here is the diff:"
+        echo "ERROR: Code is not formatted correctly. Here is the diff:"
         # Decode the Base64 diff to display it
         echo "${{ steps.clang-format.outputs.diff }}" | base64 --decode
         exit 1
       shell: bash
+
+    - name: Check for prohibited words
+      run: |
+        # Get a list of changed files
+        CHANGED_FILES=$(git diff --name-only --cached)
+
+        # Check for prohibited words only within changed files
+        if echo "$CHANGED_FILES" | xargs grep -i -E '(master|masters|slave|slaves)'; then
+          echo "ERROR: Changes introduce prohibited words (master, masters, slave, slaves). Please revise your code."
+          exit 1
+        fi
